### ISSUE TITLE
trying to install raspi-config

### ISSUE THREAD

**Issue by Sheng-IoT** [sartura/replica#10]
There is an official Raspberry Pi configuration tool called [raspi-config](https://www.raspberrypi.org/documentation/computers/configuration.html), It has a user-friendly and self-explanatory user interface, can we pre-install it? Or can we migrate tools like raspi-config to this image?

**Comment by kkcloudy** [comment]
I pre-install the dependent package dev-libs/newt from geetoo repository and when I download the raspi-config source code and copy it into an running rpi4 OS, the tool developed in shell script language and it can work normally, so we want to know how to pre-install the raspi-config to this image?

**Comment by jpetrina** [comment]
We are currently in the process of researching support for the Debian user-space on the Raspberry Pi 4 target and we will determine whether `raspi-config` will be supported for the target platform.
