### ISSUE TITLE
how to add new drivers

### ISSUE THREAD

**Issue by Sheng-IoT** [sartura/replica#11]
We learned that replica downloads kernel source code from raspberry pi’s website, if we want to add a new driver, how to do it? Our current approach is to do cross-compile and generate a driver module for later usages, are there any other ways to do this? Is there a patch-like method to change the kernel’s source code?

**Comment by jpetrina** [comment]
New drivers can be added either by: (1) pre-compiling out-of-tree kernel modules for the target kernel version and simply adding them as kernel shared objects (`.ko` files) to the overlay mechanism, or by (2) forking the upstream Linux repository and [changing the target repository in Replica](https://github.com/sartura/replica/blob/master/targets/rpi4.docker#L8) to build the specific fork.

Although Portage supports patching, one of our design goals has been to avoid introducing patch files for the kernel in the repository tree; we prefer having upstreamed all patches before building production images. However, for development efforts we maintain a [fork of the Linux kernel repository](https://github.com/sartura/linux/branches) which we use to build development images and as a staging area for the upstreaming process.

**Comment by jsmolic** [comment]
@Sheng-IoT This is now documented in the [wiki pages](https://github.com/sartura/replica/wiki/Adding-new-kernel-drivers), let me know if you have any additional questions regarding adding kernel drivers. Thanks!
