### ISSUE TITLE
change the config.txt file 

### ISSUE THREAD

**Issue by Sheng-IoT** [sartura/replica#12]
we are looking for an approach to  **pre-config** the **config.txt** so that we don't need to manually edit the **config.txt** file each time after we burn the images, so that the edited **config.txt** file will have the new settings right out of the box.

**Comment by jpetrina** [comment]
The `config.txt` file can be updated or replaced during the build process in variety of ways:

1. via the `overlay` mechanism, simply by replacing the existing file in the target image
2. using the target definition file, by changing existing `config.txt` image
3. preparing additional packages and/or patches for the existing packages

In our experience, we believe (1) or (2) would currently be the easiest approach.
