### ISSUE TITLE
TN48M-P support

### ISSUE THREAD

**Issue by jmpolom** [sartura/replica#15]
Is the Delta TN48M-P supported by replica at this time? I see in the wiki the TN48M is mentioned but it's not clear if that refers specifically and __only__ to the non-POE, single PSU TN48M or is the entire TN48M family (TN48M, TN48M2, TN48M-P).

cc: @storrgie

**Comment by robimarko** [comment]
Yes, TN48M-P is supported, a basic PoE driver is provided as well under hwmon.
I cannot tell you about the M2 model as I don't have it or docs on it.

**Comment by jmpolom** [comment]
Thanks. Can you update the wiki documentation to be more specific about the supported devices (IE: TN48M-P is supported but not TN48M2)?

Otherwise I would say we've reached closure criteria for this issue.

**Comment by jpetrina** [comment]
@jmpolom agreed, the documentation should specify supported models.

I've updated the wiki page with [a new supported models section](https://github.com/sartura/replica/wiki/Delta-TN48M#supported-models). I'll go ahead and close this issue, thanks!
