### ISSUE TITLE
docker: Error response from daemon: pull access denied

### ISSUE THREAD

**Issue by Sheng-IoT** [sartura/replica#18]
I am trying to install docker-ce on the new image with the **dev/rpi4-deboostrap** branch, now I am using [convenience script](https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script) to install docker as it seems to be the recommended way to do it on a raspberry pi, then I got this error:
`Sub-process /usr/bin/dpkg returned an error code(1)`
then I checked the sylog and got this:

> Oct 13 11:11:08 localhost systemd[1]: Starting Docker Application Container Engine...
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.614012235Z" level=info msg="Starting up"
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.615389494Z" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.616881272Z" level=info msg="parsed scheme: \"unix\"" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.616958901Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.617021790Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.617054512Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.619587234Z" level=info msg="parsed scheme: \"unix\"" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.619654142Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.619722994Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
> Oct 13 11:11:08 localhost dockerd[871]: time="2021-10-13T11:11:08.619762623Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.268837977Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.274909791Z" level=warning msg="Unable to find memory controller"
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.275823569Z" level=info msg="Loading containers: start."
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.282024475Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/5.10.63\n, error: exit status 1"
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.289257826Z" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `iptables/1.8.7 Failed to initialize nft: Protocol not supported`, error: exit status 1"
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.303592713Z" level=warning msg="Failed to read iptables version: exit status 1"
> Oct 13 11:11:09 localhost dockerd[871]: time="2021-10-13T11:11:09.436907546Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
> Oct 13 11:11:09 localhost dockerd[871]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables/1.8.7 Failed to initialize nft: Protocol not supported
> Oct 13 11:11:09 localhost dockerd[871]:  (exit status 1)
> Oct 13 11:11:09 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
> Oct 13 11:11:09 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
> Oct 13 11:11:09 localhost systemd[1]: Failed to start Docker Application Container Engine.
> Oct 13 11:11:11 localhost systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
> Oct 13 11:11:11 localhost systemd[1]: Stopped Docker Application Container Engine.
> Oct 13 11:11:11 localhost systemd[1]: Starting Docker Application Container Engine...
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.601415374Z" level=info msg="Starting up"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.603030374Z" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.607904503Z" level=info msg="parsed scheme: \"unix\"" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.608144947Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.608309614Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.608375040Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.612480632Z" level=info msg="parsed scheme: \"unix\"" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.612631021Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.612708558Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.612798484Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.636031573Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.640104832Z" level=warning msg="Unable to find memory controller"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.640572924Z" level=info msg="Loading containers: start."
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.645719498Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/5.10.63\n, error: exit status 1"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.652686997Z" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `iptables/1.8.7 Failed to initialize nft: Protocol not supported`, error: exit status 1"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.664051347Z" level=warning msg="Failed to read iptables version: exit status 1"
> Oct 13 11:11:11 localhost dockerd[924]: time="2021-10-13T11:11:11.791234311Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
> Oct 13 11:11:11 localhost dockerd[924]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables/1.8.7 Failed to initialize nft: Protocol not supported
> Oct 13 11:11:11 localhost dockerd[924]:  (exit status 1)
> Oct 13 11:11:11 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
> Oct 13 11:11:11 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
> Oct 13 11:11:11 localhost systemd[1]: Failed to start Docker Application Container Engine.
> Oct 13 11:11:13 localhost systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
> Oct 13 11:11:13 localhost systemd[1]: Stopped Docker Application Container Engine.
> Oct 13 11:11:13 localhost systemd[1]: docker.service: Start request repeated too quickly.
> Oct 13 11:11:13 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
> Oct 13 11:11:13 localhost systemd[1]: Failed to start Docker Application Container Engine.
> Oct 13 11:11:13 localhost systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
> Oct 13 11:17:01 localhost CRON[979]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
> Oct 13 11:18:13 localhost systemd[1]: Starting Cleanup of Temporary Directories...
> Oct 13 11:18:13 localhost systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
> Oct 13 11:18:13 localhost systemd[1]: Finished Cleanup of Temporary Directories.

I assumed that the problem is caused by iptables failed and then I ran` iptables -V` and I got this:

`iptables/1.8.7 failed to initialize nft: protocol not supported`

after made some research, I found a possible workaround, which is to switch to the legacy version of iptables:
`update-alternatives --set iptables /usr/sbin/iptables-legacy`
now when I ran ` iptables -V` ,the output is `iptables v1.8.7(legacy)`
and then run the **convenience script** again, now docker "seems" to be installed properly, and `docker version` returns:

> Client: Docker Engine - Community
>  Version:           20.10.9
>  API version:       1.41
>  Go version:        go1.16.8
>  Git commit:        c2ea9bc
>  Built:             Mon Oct  4 16:09:02 2021
>  OS/Arch:           linux/arm64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.9
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.8
>   Git commit:       79ea9d3
>   Built:            Mon Oct  4 16:07:12 2021
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.4.11
>   GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
>  runc:
>   Version:          1.0.2
>   GitCommit:        v1.0.2-0-g52b36a2
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

but `systemctl status docker `shows that some modules couldn't be loaded:

> ● docker.service - Docker Application Container Engine
>      Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>      Active: active (running) since Wed 2021-10-13 11:36:00 UTC; 5min ago
> TriggeredBy: ● docker.socket
>        Docs: https://docs.docker.com
>    Main PID: 1200 (dockerd)
>       Tasks: 9
>         CPU: 711ms
>      CGroup: /system.slice/docker.service
>              └─1200 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
> 
> Oct 13 11:35:59 localhost dockerd[1200]: time="2021-10-13T11:35:59.955605735Z" level=info msg="Loading containers: start."
> Oct 13 11:35:59 localhost dockerd[1200]: time="2021-10-13T11:35:59.960700573Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/5.10.63\n, error: exit status 1"
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.123529088Z" level=warning msg="Could not load necessary modules for IPSEC rules: protocol not supported"
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.139176416Z" level=warning msg="Could not load necessary modules for Conntrack: Running modprobe nf_conntrack_netlink failed with message: `modprobe: WARNING: Module nf_conntrack_netlink not found in directory /lib/modules/5.10.63`, error: exit status 1"
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.140103969Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.246448177Z" level=info msg="Loading containers: done."
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.296640169Z" level=info msg="Docker daemon" commit=79ea9d3 graphdriver(s)=overlay2 version=20.10.9
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.297143760Z" level=info msg="Daemon has completed initialization"
> Oct 13 11:36:00 localhost systemd[1]: Started Docker Application Container Engine.
> Oct 13 11:36:00 localhost dockerd[1200]: time="2021-10-13T11:36:00.369075488Z" level=info msg="API listen on /run/docker.sock"
> 

finally I tested docker run docker-hello, and it seems that the pull access is denied:
```
#docker run docker-hello
Unable to find image 'docker-hello:latest' locally
docker: Error response from daemon: pull access denied for docker-hello, repository does not exist or may require 'docker login': denied； requested access to the resource is denied.
See 'docker run --help'.
```

Even though right now we are only installing docker manually, we are planning to create an image with docker installed by default. I am not sure whether the **Custom Debian packaging** is going to help.

**Comment by Sheng-IoT** [comment]
@jpetrina hi, please check the updated issue, sorry about the late response.

**Comment by jela1337** [comment]
Hi @Sheng-IoT ,
there have been changes relevant to this issue in `master`. You can try to install **docker** again with the changes applied.

**Comment by Sheng-IoT** [comment]
@jela1337 Hi, I installed docker using the convenience script, then I ran the "docker run hello-world", now it works, except I need to run `apt-get install ca-certificates before I run  `curl -fsSL https://get.docker.com -o get-docker.sh`, otherwise I will get the error 

> curl: (77) error setting certificate verify locations: CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none

but after I installed ca-certificates, the problem has gone. Thank you!

**Comment by jsmolic** [comment]
@Sheng-IoT Thanks for the feedback, closing the issue given all problems are resolved
