### ISSUE TITLE
Mellanox SN2010 loading

### ISSUE THREAD

**Issue by jmpolom** [sartura/replica#20]
The video showing flashing the SN2010 image in the [wiki](https://github.com/sartura/replica/wiki/Mellanox-SN2010#additional-resources) seems to actually show the process for a  Delta TN48M and not a Mellanox SN2010.

Can this be updated to show the process for loading the SN2010 image on an actual SN2010?

**Comment by jpetrina** [comment]
> Good catch, we will replace the asciinema video with appropriate one for the SN2010 platform.

The [Mellanox SN2010 wiki page](https://github.com/sartura/replica/wiki/Mellanox-SN2010) has been updated with appropriate asciinema videos.
