### ISSUE TITLE
please drop brctl

### ISSUE THREAD

**Issue by lperkov** [sartura/replica#22]
For the switch profile please drop the brctl command by default. Bridges can be configured using ip utility.

I don't know if this is installed by busybox or some other tool...

Thoughts @robimarko @jpetrina @jsmolic

**Comment by robimarko** [comment]
It should be part of Busybox, so I would advise against modifying the default Busybox config.
That would mean that we need to keep track of Busybox updates and maintain our own config.

@lperkov Can you share the reason behind the need to drop it?
