### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by lperkov** [sartura/replica#23]
Lets rename the default branch to main. Please do that for the all replica-related repositories.

**Comment by jpetrina** [comment]
Thanks, this has been done for the following repositories:

* [sartura/replica](https://github.com/sartura/replica)
* [sartura/replica-overlay-main](https://github.com/sartura/replica-overlay-main)

I would suggest leaving [sartura/linux](https://github.com/sartura/linux) as-is given that upstream [[1]](https://github.com/torvalds/linux) [[2]](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/refs/) still uses `master`.
