### ISSUE TITLE
Wiki page *Edgecore AS5114 48X*: Missing images

### ISSUE THREAD

**Issue by paulmenzel** [sartura/replica#34]
The images on the Wiki page for the [Edgecore AS5114-48X](https://github.com/sartura/replica/wiki/Edgecore-AS5114-48X) do not load.

    $ curl https://camo.githubusercontent.com/e34526da3fc15ca2be80a9a8062ee29c59bd6cbacf8f1324c3d5b42ed00099e6/68747470733a2f2f7777772e656467652d636f72652e636f6d2f74696d7468756d622e7068703f7372633d5f75706c6f61642f696d616765732f323031323233313031343539312e706e6726683d3139323026773d31303830267a633d33
    Error Fetching Resource

**Comment by jpetrina** [comment]
Thanks for reporting, should be fixed now.
