### ISSUE TITLE
New Firmware build issue in tn4810m/tn48m

### ISSUE THREAD

**Issue by DhimanAirao** [sartura/replica#47]
While compiling new firmware for tn4810m I faced the following issue. This might be because `/bin/bash -l -c` need commands in double-quotes. please help me debug it.

![Screenshot from 2023-06-19 17-27-52](https://github.com/sartura/replica/assets/39194002/b5040c65-8a5e-4bbe-9fe5-7629b563567d)

**Comment by robimarko** [comment]
Did you run `git submodule init` and then `git submodule update` after cloning the repo?

**Comment by DhimanAirao** [comment]
Yes, I performed `git submodule init` and `git submodule update` after cloning repo.  

My make command is this: 
`make J=8 V=10 NO_CACHE=1 CTARGET=aarch64-unknown-linux-gnu package_tn4810m`

Is there any problem with make comamnd?

System Information:
OS: Manjaro Linux(23.0.0)
DISTRIBUTION: GNOME
CPU cores: 8
RAM: 8GB

**Comment by robimarko** [comment]
Please use `V=1` and dont use `NO_CACHE`.
If that fails, can you post the whole log as its compiling fine for me.

**Comment by DhimanAirao** [comment]
Hii, this time I execute following command but still error persist. I attached log file for your reference.

`make J=8 V=1 CTARGET=aarch64-unknown-linux-gnu package_tn4810m`
[log.txt](https://github.com/sartura/replica/files/11797195/log.txt)

**Comment by robimarko** [comment]
Ok, so its failling to download `zlib`.
I would suggest passing Gentoo mirrors that are near you via `GENTOO_MIRRORS=` from:
https://www.gentoo.org/downloads/mirrors/

**Comment by DhimanAirao** [comment]
I think this is not a issue related to mirror as when I tried to download `zlib` in my own system it still fails.  As url`(https://zlib.net/zlib-1.2.11.tar.gz)` which replica uses to download `zlib` uses didn't exists. 

Can you say how to change zlib download url in replica?

![Screenshot from 2023-06-20 14-20-58](https://github.com/sartura/replica/assets/39194002/12c8183f-e5c5-4939-989b-4ed5109e8be4)
![Screenshot from 2023-06-20 14-22-43](https://github.com/sartura/replica/assets/39194002/8aba6716-009e-4297-94a0-a061e4f318ca)

**Comment by robimarko** [comment]
That is exactly why I am saying to add mirrors as genkernel is using an older zlib version and `zlib.net` only hosts the latest version but mirrors should have the older version as well.

If that doesn't work, you can edit `repos/gentoo/sys-kernel/genkernel/genkernel-4.3.2.ebuild` to use `https://www.zlib.net/fossils/zlib-1.2.11.tar.gz` instead.

**Comment by DhimanAirao** [comment]
Hello, tried multiple mirrors(China, Japan ,US) still issue persist and also tried by modifying `repos/gentoo/sys-kernel/genkernel/genkernel-4.3.2.ebuild` then it was not able to extract `ERROR: sys-kernel/genkernel-4.3.2::gentoo failed (unpack phase):`  Can you tell which mirrors you are using so I can try with it?

**Comment by robimarko** [comment]
I am using:
`GENTOO_MIRRORS="http://gentoo.wheel.sk/ http://mirrors.evowise.com/gentoo/"`

As they are much faster than the default ones where I live

**Comment by DhimanAirao** [comment]
Hello, your mirrors worked for me too. Thank you for your help and support.

**Comment by DhimanAirao** [comment]
Can you please tell me how to add custom packages in firmware build as I cannot see and documentation related to it in repo?

**Comment by paulmenzel** [comment]
As a lurker, I’d appreciate it, if you opened a new issue for this.

**Comment by robimarko** [comment]
I dont think there are any docs for it, but you can just specify more packages in:
`https://github.com/sartura/replica-overlay-switch/blob/main/profiles/replica/armada7040-prestera/packages`

Basically, docs for Gentoo apply here.

**Comment by DhimanAirao** [comment]
I think this will only provide us the packages which are available in Gentoo packages. What I want is if I have some custom package stored in my local machine. So how to add that during firmware build?

**Comment by robimarko** [comment]
For that, you can either add a custom ebuild to the switch ebuild repo or add your own ebuild repository and include it.
Everything relating to ebuilds and ebuild repos is documented already in Gentoo docs

**Comment by paulmenzel** [comment]
With commit https://github.com/sartura/replica/commit/f01924d239f973d09e57b1b4e580e67eaf0ff34c I ran

    make -j32 DOCKER_BUILDKIT=1 CTARGET=armv7a-unknown-linux-musleabihf package_tn4810m  GENTOO_MIRRORS="http://gentoo.wheel.sk/ http://mirrors.evowise.com/gentoo/"

but still got the error.

**Comment by paulmenzel** [comment]
Could you please share the correct line?

**Comment by jpetrina** [comment]
> Could you please share the correct line?

Paul, could you please give us more details so we could follow up accordingly?

**Comment by paulmenzel** [comment]
Sorry, it worked trying it on the weekend. One mistake in my line is `CTARGET=armv7a-unknown-linux-musleabihf`, and should be `CTARGET=aarch64-unknown-linux-gnu`. From my side, I can’t reproduce it anymore with the command below:

    make -j32 DOCKER_BUILDKIT=1 CTARGET=aarch64-unknown-linux-gnu package_tn48m GENTOO_MIRRORS=" http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/ http://gentoo.wheel.sk/ http://mirrors.evowise.com/gentoo/"

**Comment by jpetrina** [comment]
Thanks, I am closing this issue.

@DhimanAirao, please feel free to open up a new issue regarding custom package integration though.
