### ISSUE TITLE
Build fails with: `One of the following masked packages is required to complete your request: dev-python/autocommand-2.2.2::gentoo (masked by: ) dependency required by "dev-python/jaraco-text-3.11.1::gentoo" [installed])`

### ISSUE THREAD

**Issue by paulmenzel** [sartura/replica#48]
After updating to commit 67fdefc, I get a different error than in issue https://github.com/sartura/replica/issues/47.

    $ more /etc/os-release
    PRETTY_NAME="Debian GNU/Linux trixie/sid"
    NAME="Debian GNU/Linux"
    VERSION_CODENAME=trixie
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    $ git log --oneline --no-decorate -3
    67fdefc config: savedconfig: busybox: use for v1.36.1
    efe55a2 Update Gentoo stage3 and repositories to 20230717
    f01924d Update Gentoo stage3 and repositories to 20230320
    $ make -j32 DOCKER_BUILDKIT=1 CTARGET=armv7a-unknown-linux-musleabihf package_tn48m GENTOO_MIRRORS="http://gentoo.wheel.sk/ http://mirrors.evowise.com/gentoo/"
    […]
    /stage3:amd64-openrc-20230717
    amd64-openrc-20230717: Pulling from gentoo/stage3
    Digest: sha256:850f2efbd044de09feb75dbf68837988c7f2b5d29d099fee357734744db70b60
    Status: Image is up to date for gentoo/stage3:amd64-openrc-20230717
    docker.io/gentoo/stage3:amd64-openrc-20230717
    docker build . -f targets/tn48m.cache --build-arg CTARGET="armv7a-unknown-linux-musleabihf" --build-arg BUILDKIT_INLINE_CACHE=1 --secret id=env,src=et
    […]
    #13 95.65 !!! All ebuilds that could satisfy "dev-python/autocommand[python_targets_pypy3(-)?,python_targets_python3_9(-)?,python_targets_python3_10(.
    #13 95.65 !!! One of the following masked packages is required to complete your request:
    #13 95.65 - dev-python/autocommand-2.2.2::gentoo (masked by: )
    #13 95.65
    #13 95.65 (dependency required by "dev-python/jaraco-text-3.11.1::gentoo" [installed])
    #13 95.65 (dependency required by "dev-python/setuptools-67.8.0-r1::gentoo" [installed])
    #13 95.65 (dependency required by "dev-python/jinja-3.1.2::gentoo" [installed])
    #13 95.65 (dependency required by "sys-auth/pambase-20220214::gentoo" [installed])
    #13 95.65 (dependency required by "sys-libs/pam-1.5.2-r3::gentoo" [ebuild])    
    #13 95.65 (dependency required by "sys-apps/util-linux-2.38.1::gentoo[pam]" [ebuild])
    #13 95.65 (dependency required by "sys-apps/gptfdisk-1.0.9-r2::gentoo[-static]" [ebuild])
    #13 95.65 (dependency required by "@system" [set])
    #13 95.65 (dependency required by "@world" [argument])
    #13 95.65 For more information, see the MASKED PACKAGES section in the emerge  
    #13 95.65 man page or refer to the Gentoo Handbook.
    #13 95.65
    ------

[Full log](https://github.com/sartura/replica/files/12136546/20230722-replica.txt)

**Comment by robimarko** [comment]
`CTARGET=armv7a-unknown-linux-musleabihf` is definitively incorrect for TN48M since its ARMv8 device.
musl builds for TN48M are not supported as systemd wont work, so please use:
`CTARGET=aarch64-unknown-linux-gnu`

Did you run `git submodule update` after pulling in newer commits?

**Comment by jpetrina** [comment]
Hi Paul,

have you encountered this issue again in the meanwhile?

**Comment by paulmenzel** [comment]
Sorry, I missed your reply. I didn’t see it in issue https://github.com/sartura/replica/issues/49 with the same commit, so it might have been caused by the incorrect `CTARGET=` setting.
